# Generated by Django 4.1 on 2022-08-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaleCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('height', models.IntegerField(null=True)),
                ('shoulder', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('chest', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('tummy', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('waist', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('sleeve_length', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('sleeve_round', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('links', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('neck', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('lap', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('trouser_length', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('boot', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('knee', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
